import School0 from "../../assets/img/school/School0.png"
import School1 from "../../assets/img/school/School1.png"
import School2 from "../../assets/img/school/School2.png"
import School3 from "../../assets/img/school/School3.png"
import School4 from "../../assets/img/school/School4.png"
import School5 from "../../assets/img/school/School5.png"
import School6 from "../../assets/img/school/School6.png"
import School7 from "../../assets/img/school/School7.png"
import School8 from "../../assets/img/school/School8.png"
import School9 from "../../assets/img/school/School9.png"
import School10 from "../../assets/img/school/School10.png"
import School11 from "../../assets/img/school/School11.png"
import School12 from "../../assets/img/school/School12.png"
import School13 from "../../assets/img/school/School13.png"
import School14 from "../../assets/img/school/School14.png"
import School15 from "../../assets/img/school/School15.png"
import School16 from "../../assets/img/school/School16.png"
import School17 from "../../assets/img/school/School17.png"
import School18 from "../../assets/img/school/School18.png"
import School19 from "../../assets/img/school/School19.png"
import School20 from "../../assets/img/school/School20.png"
import School21 from "../../assets/img/school/School21.png"
import School22 from "../../assets/img/school/School22.png"
import School23 from "../../assets/img/school/School23.png"
import School24 from "../../assets/img/school/School24.png"
import School25 from "../../assets/img/school/School25.png"
import School26 from "../../assets/img/school/School26.png"
import School27 from "../../assets/img/school/School27.png"
import School28 from "../../assets/img/school/School28.png"
import School29 from "../../assets/img/school/School29.png"
import School30 from "../../assets/img/school/School30.png"
import School31 from "../../assets/img/school/School31.png"

export const schoolImages = {
    School0, School1, School2, School3, School4, School5, School6, School7, School8, School9, School10, School11, School12, School13, School14, School15, School16, School17, School18, School19, School20, School21, School22, School23, School24, School25, School26, School27, School28, School29, School30, School31
}